"""create_notes_schema

Revision ID: 2fbf92d6a04f
Revises: 
Create Date: 2026-09-24 13:26:01.502059
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2fbf92d6a04f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('labels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=120), server_default='', nullable=False),
    sa.Column('color', sa.String(length=32), server_default='paper', nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_labels_name'), 'labels', ['name'], unique=False)
    op.create_table('notes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=500), server_default='', nullable=False),
    sa.Column('rich_text_content', sa.Text(), server_default='', nullable=False),
    sa.Column('content_format', sa.String(length=32), server_default='html', nullable=False),
    sa.Column('plain_text_content', sa.Text(), server_default='', nullable=False),
    sa.Column('note_type', sa.String(length=32), server_default='text', nullable=False),
    sa.Column('color', sa.String(length=32), server_default='paper', nullable=False),
    sa.Column('is_pinned', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_archived', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_trashed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trashed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notes_workspace', 'notes', ['is_trashed', 'is_archived', 'is_pinned', 'sort_order'], unique=False)
    op.create_table('checklist_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('note_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), server_default='', nullable=False),
    sa.Column('is_completed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_checklist_note_order', 'checklist_items', ['note_id', 'sort_order'], unique=False)
    op.create_table('note_labels',
    sa.Column('note_id', sa.Integer(), nullable=False),
    sa.Column('label_id', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['label_id'], ['labels.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('note_id', 'label_id')
    )
    op.create_index(op.f('ix_note_labels_label_id'), 'note_labels', ['label_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_note_labels_label_id'), table_name='note_labels')
    op.drop_table('note_labels')
    op.drop_index('ix_checklist_note_order', table_name='checklist_items')
    op.drop_table('checklist_items')
    op.drop_index('ix_notes_workspace', table_name='notes')
    op.drop_table('notes')
    op.drop_index(op.f('ix_labels_name'), table_name='labels')
    op.drop_table('labels')
    # ### end Alembic commands ###
